
- name: Store Secrets with Vault
  shell: vault kv put secret/github git_access_user="{{ user }}" git_access_password="{{ token }}"
  run_once: true
  environment:
    VAULT_ADDR: "{{ lookup('env', 'VAULT_ADDR') }}"
    VAULT_TOKEN: "{{ lookup('env', 'vault_master_token') }}"